# menu_data.py — Menu complet Miss Chawarma (source : MenuSection.tsx du site)
# Structure : liste de catégories, chacune avec ses plats.
# "price" = prix numérique utilisé pour le panier. "label" = affichage si différent.

MENU_DATA = [
    {
        "name_fr": "Mezzé chauds", "name_en": "Hot Mezzés",
        "subtitle_fr": "Spécialités chaudes", "subtitle_en": "Hot specialties",
        "dishes": [
            {"name_fr": "Hallou'me", "name_en": "Hallou'me", "price": 8.90,
             "short_fr": "Fromage de chèvre, thym, tomates et huile d'olive.",
             "short_en": "Goat cheese, thyme, tomatoes and olive oil.",
             "image": "/images/halloume.jpeg",
             "comp_fr": ["Fromage halloumi", "Thym frais", "Tomates cerises", "Huile d'olive extra vierge"],
             "comp_en": ["Halloumi cheese", "Fresh thyme", "Cherry tomatoes", "Extra virgin olive oil"],
             "all_fr": ["Lait"], "all_en": ["Milk"]},
            {"name_fr": "Hommous avec Chawarma", "name_en": "Hommous with Chawarma", "price": 8.90,
             "short_fr": "Purée de pois chiche, viande hachée, pignons de pin, paprika et coriandre.",
             "short_en": "Chickpea puree, minced meat, pine nuts, paprika and coriander.",
             "image": "/images/houmous chawarma.jpeg",
             "comp_fr": ["Pois chiche", "Tahina", "Viande hachée", "Pignons de pin", "Paprika", "Coriandre", "Huile d'olive", "Citron"],
             "comp_en": ["Chickpeas", "Tahini", "Minced meat", "Pine nuts", "Paprika", "Coriander", "Olive oil", "Lemon"],
             "all_fr": ["Sésame", "Fruits à coque"], "all_en": ["Sesame", "Tree nuts"]},
            {"name_fr": "Batata harra", "name_en": "Batata harra", "price": 8.90,
             "short_fr": "Pommes de terre sautées à l'ail et coriandre.",
             "short_en": "Sautéed potatoes with garlic and coriander.",
             "image": "/images/batatahara.jpeg",
             "comp_fr": ["Pommes de terre", "Ail", "Coriandre fraîche", "Piment rouge", "Huile d'olive"],
             "comp_en": ["Potatoes", "Garlic", "Fresh coriander", "Red chili", "Olive oil"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Makanek fait maison", "name_en": "Homemade Makanek", "price": 8.90,
             "short_fr": "Saucisse de bœuf et mélasse de grenade.",
             "short_en": "Beef sausage with pomegranate molasses.",
             "image": "/images/makanek (2).jpeg",
             "comp_fr": ["Viande de bœuf", "Épices orientales", "Mélasse de grenade", "Pins grillés"],
             "comp_en": ["Beef", "Oriental spices", "Pomegranate molasses", "Toasted pine nuts"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Soujouk fait maison", "name_en": "Homemade Soujouk", "price": 8.90,
             "short_fr": "Saucisse de bœuf épicée.",
             "short_en": "Spicy beef sausage.",
             "image": "/images/makanek.jpeg",
             "comp_fr": ["Viande de bœuf", "Paprika", "Cumin", "Ail", "Piment"],
             "comp_en": ["Beef", "Paprika", "Cumin", "Garlic", "Chili"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Sawda poulet", "name_en": "Chicken Sawda", "price": 8.90,
             "short_fr": "Foie de volaille sauté à l'ail, coriandre, mélasse de grenade et citron.",
             "short_en": "Chicken liver sautéed with garlic, coriander, pomegranate molasses and lemon.",
             "image": "/images/sawda.jpg",
             "comp_fr": ["Foie de volaille", "Ail", "Coriandre fraîche", "Mélasse de grenade", "Citron"],
             "comp_en": ["Chicken liver", "Garlic", "Fresh coriander", "Pomegranate molasses", "Lemon"],
             "all_fr": [], "all_en": []},
        ],
    },
    {
        "name_fr": "Mezzé froids", "name_en": "Cold Mezzés",
        "subtitle_fr": "Fraîcheur libanaise", "subtitle_en": "Lebanese freshness",
        "dishes": [
            {"name_fr": "Hommous", "name_en": "Hommous", "price": 7.50,
             "short_fr": "Purée de pois chiche, tahina, citron et huile d'olive.",
             "short_en": "Chickpea puree, tahini, lemon and olive oil.",
             "image": "/images/hoummous.jpeg",
             "comp_fr": ["Pois chiche", "Tahina (crème de sésame)", "Citron", "Ail", "Huile d'olive"],
             "comp_en": ["Chickpeas", "Tahini (sesame cream)", "Lemon", "Garlic", "Olive oil"],
             "all_fr": ["Sésame"], "all_en": ["Sesame"]},
            {"name_fr": "Baba Ghanouj / Mouttabbal", "name_en": "Baba Ghanouj / Mouttabbal", "price": 7.50,
             "short_fr": "Aubergine à la crème de sésame, citron et huile d'olive.",
             "short_en": "Eggplant with sesame cream, lemon and olive oil.",
             "image": "/images/mttabel.jpeg",
             "comp_fr": ["Aubergine grillée", "Tahina", "Citron", "Ail", "Huile d'olive", "Persil"],
             "comp_en": ["Grilled eggplant", "Tahini", "Lemon", "Garlic", "Olive oil", "Parsley"],
             "all_fr": ["Sésame"], "all_en": ["Sesame"]},
            {"name_fr": "Labné à la libanaise", "name_en": "Lebanese Labné", "price": 7.50,
             "short_fr": "Fromage blanc, thym, menthe et huile d'olive.",
             "short_en": "Strained yogurt cheese, thyme, mint and olive oil.",
             "image": "/images/labnealalibanaise.jpeg",
             "comp_fr": ["Fromage blanc égoutté", "Zaatar (thym libanais)", "Menthe fraîche", "Huile d'olive"],
             "comp_en": ["Strained yogurt cheese", "Zaatar (Lebanese thyme)", "Fresh mint", "Olive oil"],
             "all_fr": ["Lait"], "all_en": ["Milk"]},
            {"name_fr": "Moussaka", "name_en": "Moussaka", "price": 7.50,
             "short_fr": "Aubergine grillée, pois chiche et sauce tomate.",
             "short_en": "Grilled eggplant, chickpeas and tomato sauce.",
             "image": "/images/moussaka.jpeg",
             "comp_fr": ["Aubergine", "Pois chiche", "Tomates", "Ail", "Oignons", "Huile d'olive"],
             "comp_en": ["Eggplant", "Chickpeas", "Tomatoes", "Garlic", "Onions", "Olive oil"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Mojadara", "name_en": "Mojadara", "price": 7.50,
             "short_fr": "Lentilles et riz aux oignons caramélisés.",
             "short_en": "Lentils and rice with caramelized onions.",
             "image": "/images/Moujadara.jpg",
             "comp_fr": ["Lentilles vertes", "Riz", "Oignons caramélisés", "Cumin", "Huile d'olive"],
             "comp_en": ["Green lentils", "Rice", "Caramelized onions", "Cumin", "Olive oil"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Loubia b Zeyt", "name_en": "Loubia b Zeyt", "price": 7.50,
             "short_fr": "Haricots verts mijotés à la tomate, oignons et huile d'olive.",
             "short_en": "Green beans stewed with tomato, onions and olive oil.",
             "image": "/images/loubye.jpeg",
             "comp_fr": ["Haricots verts", "Tomates", "Oignons", "Huile d'olive", "Ail"],
             "comp_en": ["Green beans", "Tomatoes", "Onions", "Olive oil", "Garlic"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Warak Enab", "name_en": "Warak Enab", "price": 7.50,
             "short_fr": "Feuilles de vigne farcies au riz, tomates et persil.",
             "short_en": "Vine leaves stuffed with rice, tomatoes and parsley.",
             "image": "/images/warak enab.jpeg",
             "comp_fr": ["Feuilles de vigne", "Riz", "Tomates", "Persil"],
             "comp_en": ["Vine leaves", "Rice", "Tomatoes", "Parsley"],
             "all_fr": [], "all_en": []},
        ],
    },
    {
        "name_fr": "Mezzé à partager", "name_en": "Mezzé to Share",
        "subtitle_fr": "Chaud, froid et beignets variés", "subtitle_en": "Hot, cold and assorted fritters",
        "dishes": [
            {"name_fr": "Mezzé 2 personnes", "name_en": "Mezzé for 2", "price": 45.00,
             "short_fr": "7 mezzés chauds, froids et beignets variés.",
             "short_en": "7 assorted hot and cold mezzés with fritters.",
             "image": "/images/mezzePartage.jpeg",
             "comp_fr": ["7 mezzés au choix : chauds, froids et beignets assortis"],
             "comp_en": ["7 mezzés of your choice: hot, cold and assorted fritters"],
             "all_fr": ["Gluten", "Sésame", "Lait (selon choix)"], "all_en": ["Gluten", "Sesame", "Milk (depending on choice)"]},
            {"name_fr": "Mezzé 3 personnes", "name_en": "Mezzé for 3", "price": 63.00,
             "short_fr": "10 mezzés chauds, froids et beignets variés.",
             "short_en": "10 assorted hot and cold mezzés with fritters.",
             "image": "/images/mezzePartage.jpeg",
             "comp_fr": ["10 mezzés au choix : chauds, froids et beignets assortis"],
             "comp_en": ["10 mezzés of your choice: hot, cold and assorted fritters"],
             "all_fr": ["Gluten", "Sésame", "Lait (selon choix)"], "all_en": ["Gluten", "Sesame", "Milk (depending on choice)"]},
            {"name_fr": "Mezzé 4 personnes", "name_en": "Mezzé for 4", "price": 80.00,
             "short_fr": "12 mezzés chauds, froids et beignets variés.",
             "short_en": "12 assorted hot and cold mezzés with fritters.",
             "image": "/images/mezzePartage.jpeg",
             "comp_fr": ["12 mezzés au choix : chauds, froids et beignets assortis"],
             "comp_en": ["12 mezzés of your choice: hot, cold and assorted fritters"],
             "all_fr": ["Gluten", "Sésame", "Lait (selon choix)"], "all_en": ["Gluten", "Sesame", "Milk (depending on choice)"]},
            {"name_fr": "Mezzé 5 personnes", "name_en": "Mezzé for 5", "price": 95.00,
             "short_fr": "14 mezzés chauds, froids et beignets variés.",
             "short_en": "14 assorted hot and cold mezzés with fritters.",
             "image": "/images/mezzePartage.jpeg",
             "comp_fr": ["14 mezzés chauds, froids et beignets variés"],
             "comp_en": ["14 assorted hot and cold mezzés with fritters"],
             "all_fr": ["Gluten", "Sésame", "Lait (selon choix)"], "all_en": ["Gluten", "Sesame", "Milk (depending on choice)"]},
            {"name_fr": "Mezzé 6 personnes", "name_en": "Mezzé for 6", "price": 106.00,
             "short_fr": "16 mezzés chauds, froids et beignets variés.",
             "short_en": "16 assorted hot and cold mezzés with fritters.",
             "image": "/images/mezzePartage.jpeg",
             "comp_fr": ["16 mezzés chauds, froids et beignets variés"],
             "comp_en": ["16 assorted hot and cold mezzés with fritters"],
             "all_fr": ["Gluten", "Sésame", "Lait (selon choix)"], "all_en": ["Gluten", "Sesame", "Milk (depending on choice)"]},
        ],
    },
    {
        "name_fr": "Salades libanaises", "name_en": "Lebanese Salads",
        "subtitle_fr": "Fraîcheur et herbes", "subtitle_en": "Freshness and herbs",
        "dishes": [
            {"name_fr": "Mrs. Fattoush", "name_en": "Mrs. Fattoush", "price": 7.20,
             "short_fr": "Salade verte, tomates, concombres, radis, poivrons, citron et huile d'olive.",
             "short_en": "Green salad, tomatoes, cucumbers, radishes, peppers, lemon and olive oil.",
             "image": "/images/fattosh.jpeg",
             "comp_fr": ["Salade verte", "Tomates", "Concombres", "Radis", "Poivrons", "Citron", "Huile d'olive"],
             "comp_en": ["Green salad", "Tomatoes", "Cucumbers", "Radishes", "Peppers", "Lemon", "Olive oil"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Miss Tabboulé", "name_en": "Miss Tabboulé", "price": 7.20,
             "short_fr": "Persil, blé concassé, menthe, tomates, oignons, citron et huile d'olive.",
             "short_en": "Parsley, cracked wheat, mint, tomatoes, onions, lemon and olive oil.",
             "image": "/images/tabboule.jpeg",
             "comp_fr": ["Persil", "Blé concassé", "Menthe", "Tomates", "Oignons", "Citron", "Huile d'olive"],
             "comp_en": ["Parsley", "Cracked wheat", "Mint", "Tomatoes", "Onions", "Lemon", "Olive oil"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
        ],
    },
    {
        "name_fr": "Beignets", "name_en": "Fritters",
        "subtitle_fr": "Pièces libanaises", "subtitle_en": "Lebanese bites",
        "dishes": [
            {"name_fr": "Falafel", "name_en": "Falafel", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Boulette de fèves et pois chiche.",
             "short_en": "Fava bean and chickpea fritters.",
             "image": "/images/kafta1.jpeg",
             "comp_fr": ["Fèves", "Pois chiche", "Épices", "Herbes fraîches"],
             "comp_en": ["Fava beans", "Chickpeas", "Spices", "Fresh herbs"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Sambousek fromage", "name_en": "Cheese Sambousek", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Rissolé de fromage feta, graines de nigelle et persil.",
             "short_en": "Feta cheese pastry with nigella seeds and parsley.",
             "image": "/images/sambousik fromage.jpg",
             "comp_fr": ["Fromage feta", "Graines de nigelle", "Persil", "Pâte croustillante"],
             "comp_en": ["Feta cheese", "Nigella seeds", "Parsley", "Crispy pastry"],
             "all_fr": ["Gluten", "Lait"], "all_en": ["Gluten", "Milk"]},
            {"name_fr": "Sambousek viande", "name_en": "Meat Sambousek", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Rissolé de viande hachée et oignons.",
             "short_en": "Minced meat and onion pastry.",
             "image": "/images/samboussekViande.jpeg",
             "comp_fr": ["Viande hachée", "Oignons", "Épices", "Pâte croustillante"],
             "comp_en": ["Minced meat", "Onions", "Spices", "Crispy pastry"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Rikakat", "name_en": "Rikakat", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Feuilleté farci au fromage feta parfumé aux herbes.",
             "short_en": "Filo roll stuffed with herbed feta cheese.",
             "image": "/images/rikakat.jpeg",
             "comp_fr": ["Feuilleté", "Fromage feta", "Herbes"],
             "comp_en": ["Filo pastry", "Feta cheese", "Herbs"],
             "all_fr": ["Gluten", "Lait"], "all_en": ["Gluten", "Milk"]},
            {"name_fr": "Sfiha Baalbakye", "name_en": "Sfiha Baalbakye", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Tartelette de viande aux épices.",
             "short_en": "Spiced meat tartlet.",
             "image": "/images/sfihalahme.jpg",
             "comp_fr": ["Viande", "Épices", "Pâte"],
             "comp_en": ["Meat", "Spices", "Dough"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Sfiha aubergine", "name_en": "Eggplant Sfiha", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Tartelette d'aubergine, tomates et pois chiches.",
             "short_en": "Eggplant, tomato and chickpea tartlet.",
             "image": "/images/sfihaObergine.jpeg",
             "comp_fr": ["Aubergine", "Tomates", "Pois chiches", "Pâte"],
             "comp_en": ["Eggplant", "Tomatoes", "Chickpeas", "Dough"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Fatayer", "name_en": "Fatayer", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Chaussons aux épinards citronnés.",
             "short_en": "Lemony spinach turnovers.",
             "image": "/images/fatayer.jpeg",
             "comp_fr": ["Épinards", "Citron", "Pâte"],
             "comp_en": ["Spinach", "Lemon", "Dough"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Kebbé", "name_en": "Kebbé", "price": 8.90,
             "label_fr": "8,90€ / 4 pièces · 15,90€ / 8 pièces", "label_en": "8.90€ / 4 pcs · 15.90€ / 8 pcs",
             "short_fr": "Boulettes de viande hachée au blé concassé et pignons de pin.",
             "short_en": "Minced meat and cracked wheat croquettes with pine nuts.",
             "image": "/images/kebbe.jpeg",
             "comp_fr": ["Viande hachée", "Blé concassé", "Pignons de pin"],
             "comp_en": ["Minced meat", "Cracked wheat", "Pine nuts"],
             "all_fr": ["Gluten", "Fruits à coque"], "all_en": ["Gluten", "Tree nuts"]},
        ],
    },
    {
        "name_fr": "Sandwiches", "name_en": "Sandwiches",
        "subtitle_fr": "Classiques", "subtitle_en": "Classics",
        "dishes": [
            {"name_fr": "Chawarma poulet", "name_en": "Chicken Chawarma", "price": 8.90,
             "short_fr": "Poulet mariné rôti à la broche, cornichons, sauce à l'ail et frites.",
             "short_en": "Spit-roasted marinated chicken, pickles, garlic sauce and fries.",
             "image": "/images/sandpoulet.jpg",
             "comp_fr": ["Poulet mariné rôti à la broche", "Cornichons", "Sauce toum (ail)", "Frites", "Pain pita"],
             "comp_en": ["Spit-roasted marinated chicken", "Pickles", "Toum (garlic sauce)", "Fries", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Chawarma Bœuf", "name_en": "Beef Chawarma", "price": 8.90,
             "short_fr": "Bœuf mariné, persil, oignons, tomates, tahina, cornichons et batata harra.",
             "short_en": "Marinated beef, parsley, onions, tomatoes, tahini, pickles and batata harra.",
             "image": "/images/chBoeuf.jpeg",
             "comp_fr": ["Bœuf mariné", "Persil", "Oignons", "Tomates", "Tahina", "Cornichons", "Batata harra", "Pain pita"],
             "comp_en": ["Marinated beef", "Parsley", "Onions", "Tomatoes", "Tahini", "Pickles", "Batata harra", "Pita bread"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Chich taouk", "name_en": "Chich Taouk", "price": 8.90,
             "short_fr": "Poulet mariné, cornichons, salade de choux, sauce à l'ail et frites.",
             "short_en": "Marinated chicken, pickles, cabbage slaw, garlic sauce and fries.",
             "image": "/images/Sandwich Chich taouk.jpg",
             "comp_fr": ["Brochette de poulet mariné", "Cornichons", "Salade de choux", "Sauce toum", "Frites", "Pain pita"],
             "comp_en": ["Marinated chicken skewer", "Pickles", "Cabbage slaw", "Toum sauce", "Fries", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Kafta", "name_en": "Kafta", "price": 8.90,
             "short_fr": "Viande hachée, persil, oignons, tomates fraîches et crème de sésame.",
             "short_en": "Minced beef, parsley, onions, fresh tomatoes and sesame cream.",
             "image": "/images/sandkafta.jpg",
             "comp_fr": ["Viande hachée de bœuf", "Persil", "Oignons", "Tomates fraîches", "Tahina", "Pain pita"],
             "comp_en": ["Minced beef", "Parsley", "Onions", "Fresh tomatoes", "Tahini", "Pita bread"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Fahita", "name_en": "Fahita", "price": 8.90,
             "short_fr": "Émincé de poulet mariné à la sauce tomate, poivron, champignon, oignons, cornichons.",
             "short_en": "Marinated chicken strips in tomato sauce, peppers, mushrooms, onions, pickles.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Émincé de poulet", "Sauce tomate", "Poivrons", "Champignons", "Oignons", "Cornichons", "Pain pita"],
             "comp_en": ["Chicken strips", "Tomato sauce", "Peppers", "Mushrooms", "Onions", "Pickles", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Poulet crispy", "name_en": "Crispy Chicken", "price": 8.90,
             "short_fr": "Poulet mariné au curry, sauce à l'ail, tomates, salade, cornichons et frites.",
             "short_en": "Curry-marinated chicken, garlic sauce, tomatoes, lettuce, pickles and fries.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Poulet mariné au curry", "Sauce à l'ail", "Tomates", "Salade", "Cornichons", "Frites", "Pain pita"],
             "comp_en": ["Curry-marinated chicken", "Garlic sauce", "Tomatoes", "Lettuce", "Pickles", "Fries", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Sojok fait maison", "name_en": "Homemade Sojok", "price": 8.90,
             "short_fr": "Mini saucisses libanaises, sauce à l'ail, batata harra, tomates et cornichons.",
             "short_en": "Mini Lebanese sausages, garlic sauce, batata harra, tomatoes and pickles.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Mini saucisses libanaises", "Sauce à l'ail", "Batata harra", "Tomates", "Cornichons", "Pain pita"],
             "comp_en": ["Mini Lebanese sausages", "Garlic sauce", "Batata harra", "Tomatoes", "Pickles", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Makanek fait maison", "name_en": "Homemade Makanek", "price": 8.90,
             "short_fr": "Mini saucisses libanaises, mélasse de grenade, sauce à l'ail, tomates et cornichons.",
             "short_en": "Mini Lebanese sausages, pomegranate molasses, garlic sauce, tomatoes and pickles.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Mini saucisses libanaises", "Mélasse de grenade", "Sauce à l'ail", "Tomates", "Cornichons", "Pain pita"],
             "comp_en": ["Mini Lebanese sausages", "Pomegranate molasses", "Garlic sauce", "Tomatoes", "Pickles", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Kebbé", "name_en": "Kebbé", "price": 8.90,
             "short_fr": "Bœuf haché et blé, crème de sésame, oignons, tomates fraîches, cornichons.",
             "short_en": "Minced beef and wheat, sesame cream, onions, fresh tomatoes, pickles.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Bœuf haché", "Blé", "Crème de sésame", "Oignons", "Tomates", "Cornichons", "Pain pita"],
             "comp_en": ["Minced beef", "Wheat", "Sesame cream", "Onions", "Tomatoes", "Pickles", "Pita bread"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
        ],
    },
    {
        "name_fr": "Sandwiches Végétariens", "name_en": "Vegetarian Sandwiches",
        "subtitle_fr": "Végé", "subtitle_en": "Veggie",
        "dishes": [
            {"name_fr": "Falafel", "name_en": "Falafel", "price": 8.90,
             "short_fr": "Beignets de pois chiche, tomates, salade, cornichon, crème de sésame et hommous.",
             "short_en": "Chickpea fritters, tomatoes, lettuce, pickles, sesame cream and hommous.",
             "image": "/images/sandfalafel.jpg",
             "comp_fr": ["Beignets de pois chiche", "Tomates", "Salade", "Cornichons", "Tahina", "Hommous", "Pain pita"],
             "comp_en": ["Chickpea fritters", "Tomatoes", "Lettuce", "Pickles", "Tahini", "Hommous", "Pita bread"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Batata/Frites", "name_en": "Batata/Fries", "price": 8.90,
             "short_fr": "Sandwich frites, tomates, salade, ketchup, cornichons, coleslaw et sauce à l'ail.",
             "short_en": "Fries sandwich, tomatoes, lettuce, ketchup, pickles, coleslaw and garlic sauce.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Frites", "Tomates", "Salade", "Ketchup", "Cornichons", "Coleslaw", "Sauce toum", "Pain pita"],
             "comp_en": ["Fries", "Tomatoes", "Lettuce", "Ketchup", "Pickles", "Coleslaw", "Toum sauce", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Labné", "name_en": "Labné", "price": 8.90,
             "short_fr": "Fromage blanc, tomates, menthe, huile d'olive, salade et chips de zaatar.",
             "short_en": "Strained yogurt cheese, tomatoes, mint, olive oil, lettuce and zaatar chips.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Labné (fromage blanc)", "Tomates", "Menthe fraîche", "Huile d'olive", "Salade", "Chips de zaatar", "Pain pita"],
             "comp_en": ["Labné (yogurt cheese)", "Tomatoes", "Fresh mint", "Olive oil", "Lettuce", "Zaatar chips", "Pita bread"],
             "all_fr": ["Gluten", "Lait"], "all_en": ["Gluten", "Milk"]},
            {"name_fr": "Moutabal / Baba Ghanouj", "name_en": "Moutabal / Baba Ghanouj", "price": 8.90,
             "short_fr": "Aubergines, crème de sésame, salade, batata harra, tomates et huile d'olive.",
             "short_en": "Eggplants, sesame cream, lettuce, batata harra, tomatoes and olive oil.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Aubergines", "Crème de sésame", "Salade", "Batata harra", "Tomates", "Huile d'olive", "Pain pita"],
             "comp_en": ["Eggplants", "Sesame cream", "Lettuce", "Batata harra", "Tomatoes", "Olive oil", "Pita bread"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Makali", "name_en": "Makali", "price": 8.90,
             "short_fr": "Chou-fleur grillé, aubergine grillée, batata harra, tomates, salade, citron et ail.",
             "short_en": "Grilled cauliflower, grilled eggplant, batata harra, tomatoes, lettuce, lemon and garlic.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Chou-fleur grillé", "Aubergine grillée", "Batata harra", "Tomates", "Salade", "Citron", "Ail", "Pain pita"],
             "comp_en": ["Grilled cauliflower", "Grilled eggplant", "Batata harra", "Tomatoes", "Lettuce", "Lemon", "Garlic", "Pita bread"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Halloumi", "name_en": "Halloumi", "price": 8.90,
             "short_fr": "Fromage halloumi, zaatar, tomates fraîches, huile d'olive, taboulé et salade.",
             "short_en": "Halloumi cheese, zaatar, fresh tomatoes, olive oil, tabbouleh and lettuce.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Fromage halloumi grillé", "Zaatar", "Tomates fraîches", "Huile d'olive", "Taboulé", "Salade", "Pain pita"],
             "comp_en": ["Grilled halloumi cheese", "Zaatar", "Fresh tomatoes", "Olive oil", "Tabbouleh", "Lettuce", "Pita bread"],
             "all_fr": ["Gluten", "Lait"], "all_en": ["Gluten", "Milk"]},
            {"name_fr": "Miss Végé", "name_en": "Miss Végé", "price": 8.90,
             "short_fr": "Moutabal, taboulé, feuilles de vignes.",
             "short_en": "Moutabal, tabbouleh, vine leaves.",
             "image": "/images/sandkebbe.jpg",
             "comp_fr": ["Moutabal", "Taboulé", "Feuilles de vigne", "Pain pita"],
             "comp_en": ["Moutabal", "Tabbouleh", "Vine leaves", "Pita bread"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
        ],
    },
    {
        "name_fr": "Sandwiches Combos", "name_en": "Combo Sandwiches",
        "subtitle_fr": "Formules sandwich", "subtitle_en": "Sandwich deals",
        "dishes": [
            {"name_fr": "Tarbouch", "name_en": "Tarbouch", "price": 12.90,
             "short_fr": "1 sandwich, 2 beignets et une boisson.",
             "short_en": "1 sandwich, 2 fritters and a drink.",
             "image": "https://i.ibb.co/bMZyCsfp/Chat-GPT-Image-Jun-11-2026-01-57-53-PM.png",
             "comp_fr": ["1 sandwich au choix", "2 beignets assortis", "1 boisson au choix"],
             "comp_en": ["1 sandwich of your choice", "2 assorted fritters", "1 drink of your choice"],
             "all_fr": ["Gluten (selon choix)"], "all_en": ["Gluten (depending on choice)"]},
            {"name_fr": "Mez'Mix", "name_en": "Mez'Mix", "price": 13.90,
             "short_fr": "Sandwich, 2 mezzés froids et une boisson.",
             "short_en": "Sandwich, 2 cold mezzés and a drink.",
             "image": "https://i.ibb.co/XrN5QP1q/Chat-GPT-Image-Jun-11-2026-02-01-30-PM.png",
             "comp_fr": ["1 sandwich au choix", "2 mezzés froids au choix", "1 boisson au choix"],
             "comp_en": ["1 sandwich of your choice", "2 cold mezzés of your choice", "1 drink of your choice"],
             "all_fr": ["Gluten", "Sésame (selon choix)"], "all_en": ["Gluten", "Sesame (depending on choice)"]},
            {"name_fr": "Miss", "name_en": "Miss", "price": 13.90,
             "short_fr": "Sandwich, 2 baklawas ou mouhalabiyé et une boisson.",
             "short_en": "Sandwich, 2 baklavas or mouhalabiyé and a drink.",
             "image": "https://i.ibb.co/M5pDn55h/Chat-GPT-Image-Jun-11-2026-02-06-32-PM.png",
             "comp_fr": ["1 sandwich au choix", "2 baklawas ou 1 mouhalabiyé", "1 boisson au choix"],
             "comp_en": ["1 sandwich of your choice", "2 baklavas or 1 mouhalabiyé", "1 drink of your choice"],
             "all_fr": ["Gluten", "Fruits à coque (selon dessert)"], "all_en": ["Gluten", "Tree nuts (depending on dessert)"]},
            {"name_fr": "Mez'Max", "name_en": "Mez'Max", "price": 16.90,
             "short_fr": "2 sandwiches et une boisson.",
             "short_en": "2 sandwiches and a drink.",
             "image": "/images/Mezz max.jpeg",
             "comp_fr": ["2 sandwiches au choix", "1 boisson au choix"],
             "comp_en": ["2 sandwiches of your choice", "1 drink of your choice"],
             "all_fr": ["Gluten (selon choix)"], "all_en": ["Gluten (depending on choice)"]},
            {"name_fr": "Mrs.bowl", "name_en": "Mrs.bowl", "price": 11.90,
             "short_fr": "Riz libanais ou Batata Harra + Chawarma poulet ou taouk ou Falafel + 2 beignets au choix ou 2 feuilles de vigne + 1 boisson.",
             "short_en": "Lebanese rice or Batata Harra + chicken chawarma, taouk or falafel + 2 fritters or 2 vine leaves + 1 drink.",
             "image": "https://i.ibb.co/p6TtBhDx/Chat-GPT-Image-Jun-11-2026-12-07-22-AM.png",
             "comp_fr": ["Riz libanais ou Batata Harra", "Chawarma poulet ou taouk ou Falafel", "2 beignets au choix ou 2 feuilles de vigne", "1 boisson"],
             "comp_en": ["Lebanese rice or Batata Harra", "Chicken chawarma, taouk or falafel", "2 fritters or 2 vine leaves", "1 drink"],
             "all_fr": ["Gluten", "Sésame (selon choix)"], "all_en": ["Gluten", "Sesame (depending on choice)"]},
        ],
    },
    {
        "name_fr": "Plats", "name_en": "Signature Platters",
        "subtitle_fr": "Formules maison", "subtitle_en": "House platters",
        "dishes": [
            {"name_fr": "Mr. Tarbouch", "name_en": "Mr. Tarbouch", "price": 20.00,
             "short_fr": "4 assortiments de makanek et soujouk maison, 3 mezzés, 3 beignets et batata harra.",
             "short_en": "Homemade makanek and soujouk assortment, 3 mezzés, 3 fritters and batata harra.",
             "image": "/images/mr. tarbouch.jpeg",
             "comp_fr": ["Makanek maison", "Soujouk maison", "3 mezzés assortis", "3 beignets assortis", "Batata harra"],
             "comp_en": ["Homemade makanek", "Homemade soujouk", "3 assorted mezzés", "3 assorted fritters", "Batata harra"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Miss Chawarma", "name_en": "Miss Chawarma", "price": 23.00,
             "short_fr": "Duo de chawarma avec 3 assortiments proposés par le chef, 3 beignets et batata harra.",
             "short_en": "Chawarma duo with 3 chef's sides, 3 fritters and batata harra.",
             "image": "/images/misschawarma.jpeg",
             "comp_fr": ["Chawarma poulet", "Chawarma bœuf", "3 assortiments du chef", "3 beignets assortis", "Batata harra"],
             "comp_en": ["Chicken chawarma", "Beef chawarma", "3 chef's sides", "3 assorted fritters", "Batata harra"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Maison Mezze", "name_en": "Maison Mezze", "price": 25.00,
             "short_fr": "3 mezzés, 3 beignets, batata harra, brochette chich taouk et sandwich chawarma coupé.",
             "short_en": "3 mezzés, 3 fritters, batata harra, chich taouk skewer and sliced chawarma sandwich.",
             "image": "https://i.ibb.co/B5rHLX2Q/Chat-GPT-Image-Jun-11-2026-11-12-59-AM.png",
             "comp_fr": ["3 mezzés assortis", "3 beignets assortis", "Batata harra", "Brochette chich taouk", "Sandwich chawarma coupé"],
             "comp_en": ["3 assorted mezzés", "3 assorted fritters", "Batata harra", "Chich taouk skewer", "Sliced chawarma sandwich"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Mezze Royal", "name_en": "Mezze Royal", "price": 27.00,
             "short_fr": "4 mezzés, 3 beignets, batata harra, chich taouk, kafta, soujouk, makanek et boisson incluse.",
             "short_en": "4 mezzés, 3 fritters, batata harra, chich taouk, kafta, soujouk, makanek and a drink included.",
             "image": "https://i.ibb.co/gZ2N3rFG/Chat-GPT-Image-Jun-11-2026-11-15-37-AM.png",
             "comp_fr": ["4 mezzés assortis", "3 beignets assortis", "Batata harra", "Chich taouk", "Kafta", "Soujouk", "Makanek", "Boisson incluse"],
             "comp_en": ["4 assorted mezzés", "3 assorted fritters", "Batata harra", "Chich taouk", "Kafta", "Soujouk", "Makanek", "Drink included"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
        ],
    },
    {
        "name_fr": "Plats Chawarma", "name_en": "Chawarma Plates",
        "subtitle_fr": "Accompagnés de 3 assortiments", "subtitle_en": "Served with 3 sides",
        "dishes": [
            {"name_fr": "Chawarma Poulet", "name_en": "Chicken Chawarma", "price": 16.90,
             "short_fr": "Émincé de poulet mariné rôti à la broche accompagné de 3 assortiments.",
             "short_en": "Spit-roasted marinated chicken served with 3 sides.",
             "image": "/images/pouletplat.jpeg",
             "comp_fr": ["Poulet mariné rôti à la broche", "3 assortiments au choix : salade, riz, frites, hommous, etc."],
             "comp_en": ["Spit-roasted marinated chicken", "3 sides of your choice: salad, rice, fries, hommous, etc."],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Chawarma bœuf", "name_en": "Beef Chawarma", "price": 18.90,
             "short_fr": "Émincé de bœuf mariné accompagné de 3 assortiments.",
             "short_en": "Marinated beef served with 3 sides.",
             "image": "/images/plat chawarma viande.png",
             "comp_fr": ["Bœuf mariné", "3 assortiments au choix"],
             "comp_en": ["Marinated beef", "3 sides of your choice"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
        ],
    },
    {
        "name_fr": "Grillades au feu de bois", "name_en": "Wood-Fire Grills",
        "subtitle_fr": "Brochettes et mix grill", "subtitle_en": "Skewers and mixed grill",
        "dishes": [
            {"name_fr": "Chichtaouk", "name_en": "Chichtaouk", "price": 16.90,
             "short_fr": "Deux brochettes de poulet mariné au citron accompagnées de 3 assortiments.",
             "short_en": "Two lemon-marinated chicken skewers served with 3 sides.",
             "image": "/images/chichtaouk plat.jpeg",
             "comp_fr": ["2 brochettes de poulet mariné au citron", "3 assortiments au choix"],
             "comp_en": ["2 lemon-marinated chicken skewers", "3 sides of your choice"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Kafta", "name_en": "Kafta", "price": 16.90,
             "short_fr": "Deux brochettes de bœuf, persil, oignons accompagnées de 3 assortiments.",
             "short_en": "Two minced beef skewers with parsley and onions, served with 3 sides.",
             "image": "/images/plat kafta.jpeg",
             "comp_fr": ["2 brochettes de bœuf haché", "Persil", "Oignons", "3 assortiments au choix"],
             "comp_en": ["2 minced beef skewers", "Parsley", "Onions", "3 sides of your choice"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Miss Lahmé", "name_en": "Miss Lahmé", "price": 20.90,
             "short_fr": "Deux brochettes d'agneau mariné accompagnées de 3 assortiments.",
             "short_en": "Two marinated lamb skewers served with 3 sides.",
             "image": "https://i.ibb.co/1fKj0j59/Chat-GPT-Image-Jun-8-2026-09-27-24-AM.png",
             "comp_fr": ["2 brochettes d'agneau mariné", "3 assortiments au choix"],
             "comp_en": ["2 marinated lamb skewers", "3 sides of your choice"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Mix'Ta Grill", "name_en": "Mix'Ta Grill", "price": 22.90,
             "short_fr": "Chichtaouk, Kafta et lahmé accompagnés de 3 assortiments.",
             "short_en": "Chichtaouk, kafta and lahmé served with 3 sides.",
             "image": "/images/Mix'Ta Grill.jpg",
             "comp_fr": ["1 brochette chichtaouk", "1 brochette kafta", "1 brochette lahmé (agneau)", "3 assortiments au choix"],
             "comp_en": ["1 chichtaouk skewer", "1 kafta skewer", "1 lahmé (lamb) skewer", "3 sides of your choice"],
             "all_fr": [], "all_en": []},
        ],
    },
    {
        "name_fr": "Plats Découvertes", "name_en": "Discovery Plates",
        "subtitle_fr": "Assiettes découverte", "subtitle_en": "Discovery platters",
        "dishes": [
            {"name_fr": "Mrs. Végé'dream", "name_en": "Mrs. Végé'dream", "price": 14.90,
             "short_fr": "Hommous, taboulé, moutabal, fatayer, sfiha aubergine, falafel.",
             "short_en": "Hommous, tabbouleh, moutabal, fatayer, eggplant sfiha, falafel.",
             "image": "/images/Mrs Vegedream.jpeg",
             "comp_fr": ["Hommous", "Taboulé", "Moutabal", "Fatayer", "Sfiha aubergine", "Falafel"],
             "comp_en": ["Hommous", "Tabbouleh", "Moutabal", "Fatayer", "Eggplant sfiha", "Falafel"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Mrs. Falafel", "name_en": "Mrs. Falafel", "price": 14.90,
             "short_fr": "4 pièces falafels, hommous, taboulé, crème de sésame.",
             "short_en": "4 falafels, hommous, tabbouleh, sesame cream.",
             "image": "/images/Mrs falafel.jpeg",
             "comp_fr": ["4 pièces falafels", "Hommous", "Taboulé", "Crème de sésame"],
             "comp_en": ["4 falafels", "Hommous", "Tabbouleh", "Sesame cream"],
             "all_fr": ["Gluten", "Sésame"], "all_en": ["Gluten", "Sesame"]},
            {"name_fr": "Foie volaille", "name_en": "Chicken Liver", "price": 14.90,
             "short_fr": "Foie de volaille avec 3 assortiments.",
             "short_en": "Chicken liver with 3 sides.",
             "image": "https://i.ibb.co/xq69ZDD7/Chat-GPT-Image-Jun-8-2026-09-38-57-AM.png",
             "comp_fr": ["Foie de volaille", "3 assortiments"],
             "comp_en": ["Chicken liver", "3 sides"],
             "all_fr": [], "all_en": []},
        ],
    },
    {
        "name_fr": "Burgers", "name_en": "Burgers",
        "subtitle_fr": "Servis avec 2 assortiments et frites", "subtitle_en": "Served with 2 sides and fries",
        "dishes": [
            {"name_fr": "Hamburger libanais au feu de bois", "name_en": "Wood-Fire Lebanese Burger", "price": 14.90,
             "short_fr": "Steak haché, tomates, oignons grillés, coleslaw, cornichons servi avec 2 assortiments et frites.",
             "short_en": "Beef patty, tomatoes, grilled onions, coleslaw, pickles, served with 2 sides and fries.",
             "image": "https://i.ibb.co/nNgZNQDk/Chat-GPT-Image-Jun-8-2026-09-50-49-AM.png",
             "comp_fr": ["Steak haché", "Tomates", "Oignons grillés", "Coleslaw", "Cornichons", "2 assortiments", "Frites"],
             "comp_en": ["Beef patty", "Tomatoes", "Grilled onions", "Coleslaw", "Pickles", "2 sides", "Fries"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
        ],
    },
    {
        "name_fr": "Desserts", "name_en": "Desserts",
        "subtitle_fr": "Douceurs libanaises", "subtitle_en": "Lebanese sweets",
        "dishes": [
            {"name_fr": "Baklawa Cajou", "name_en": "Cashew Baklava", "price": 2.00,
             "short_fr": "Pâtisserie libanaise feuilletée au miel et aux noix de cajou.",
             "short_en": "Flaky Lebanese pastry with honey and cashews.",
             "image": "https://i.ibb.co/4ZQSfrY4/Chat-GPT-Image-Jun-11-2026-12-53-57-AM.png",
             "comp_fr": ["Pâte filo", "Noix de cajou", "Miel", "Sirop de fleur d'oranger"],
             "comp_en": ["Filo pastry", "Cashews", "Honey", "Orange blossom syrup"],
             "all_fr": ["Gluten", "Fruits à coque"], "all_en": ["Gluten", "Tree nuts"]},
            {"name_fr": "Baklawa pistache", "name_en": "Pistachio Baklava", "price": 2.50,
             "short_fr": "Pâtisserie libanaise feuilletée au miel et à la pistache.",
             "short_en": "Flaky Lebanese pastry with honey and pistachios.",
             "image": "/images/baklawa.jpg",
             "comp_fr": ["Pâte filo", "Pistaches", "Miel", "Sirop de fleur d'oranger"],
             "comp_en": ["Filo pastry", "Pistachios", "Honey", "Orange blossom syrup"],
             "all_fr": ["Gluten", "Fruits à coque"], "all_en": ["Gluten", "Tree nuts"]},
            {"name_fr": "Mouhalabiyé", "name_en": "Mouhalabiyé", "price": 4.90,
             "short_fr": "Flan libanais parfumé à la fleur d'oranger, pistaches à la rose.",
             "short_en": "Lebanese milk flan with orange blossom, rose and pistachios.",
             "image": "/images/mouhalabeya.jpeg",
             "comp_fr": ["Lait", "Amidon de maïs", "Eau de fleur d'oranger", "Pistaches", "Pétales de rose"],
             "comp_en": ["Milk", "Corn starch", "Orange blossom water", "Pistachios", "Rose petals"],
             "all_fr": ["Lait", "Fruits à coque"], "all_en": ["Milk", "Tree nuts"]},
            {"name_fr": "Maacarons libanais", "name_en": "Lebanese Maacarons", "price": 3.90,
             "short_fr": "Pâtisserie libanaise traditionnelle parfumée.",
             "short_en": "Traditional scented Lebanese pastry.",
             "image": "https://i.ibb.co/YTkCbLgQ/Chat-GPT-Image-Jun-15-2026-03-04-34-PM.png",
             "comp_fr": ["Semoule", "Sucre", "Anis", "Sirop parfumé"],
             "comp_en": ["Semolina", "Sugar", "Anise", "Scented syrup"],
             "all_fr": ["Gluten"], "all_en": ["Gluten"]},
            {"name_fr": "Namoura", "name_en": "Namoura", "price": 3.90,
             "short_fr": "Gâteau libanais à la semoule, moelleux et parfumé.",
             "short_en": "Soft, fragrant Lebanese semolina cake.",
             "image": "/images/Namoura (2).jpeg",
             "comp_fr": ["Semoule", "Sucre", "Yaourt", "Sirop parfumé"],
             "comp_en": ["Semolina", "Sugar", "Yogurt", "Scented syrup"],
             "all_fr": ["Gluten", "Lait"], "all_en": ["Gluten", "Milk"]},
            {"name_fr": "Knefeh", "name_en": "Knefeh", "price": 7.90,
             "short_fr": "Gâteau aux cheveux d'ange avec fromage, pistaches et sirop de sucre.",
             "short_en": "Angel-hair pastry with cheese, pistachios and sugar syrup.",
             "image": "https://i.ibb.co/yBQThLrV/Chat-GPT-Image-Jun-11-2026-12-59-41-AM.png",
             "comp_fr": ["Cheveux d'ange (kataïfi)", "Fromage akkawi", "Pistaches", "Sirop de sucre parfumé"],
             "comp_en": ["Kataifi (angel hair)", "Akkawi cheese", "Pistachios", "Scented sugar syrup"],
             "all_fr": ["Gluten", "Lait", "Fruits à coque"], "all_en": ["Gluten", "Milk", "Tree nuts"]},
            {"name_fr": "Sfouf", "name_en": "Sfouf", "price": 3.90,
             "short_fr": "Gâteau libanais à la semoule et au curcuma.",
             "short_en": "Lebanese semolina and turmeric cake.",
             "image": "https://i.ibb.co/FqHHB6mb/Chat-GPT-Image-Jun-11-2026-01-01-00-AM.png",
             "comp_fr": ["Semoule de blé", "Curcuma", "Anis", "Huile de tournesol", "Sucre", "Pignons de pin"],
             "comp_en": ["Wheat semolina", "Turmeric", "Anise", "Sunflower oil", "Sugar", "Pine nuts"],
             "all_fr": ["Gluten", "Fruits à coque"], "all_en": ["Gluten", "Tree nuts"]},
            {"name_fr": "Café ou Thé gourmand", "name_en": "Gourmet Coffee or Tea", "price": 7.90,
             "short_fr": "Café ou thé accompagné de deux petites pâtisseries libanaises ou 1 mouhalabiyé ou sfouf.",
             "short_en": "Coffee or tea with two small Lebanese pastries, or 1 mouhalabiyé or sfouf.",
             "image": "https://i.ibb.co/fVTkJjxS/Chat-GPT-Image-Jun-11-2026-01-06-50-AM.png",
             "comp_fr": ["Café ou thé", "2 petites pâtisseries libanaises", "Ou 1 mouhalabiyé", "Ou sfouf"],
             "comp_en": ["Coffee or tea", "2 small Lebanese pastries", "Or 1 mouhalabiyé", "Or sfouf"],
             "all_fr": ["Selon la pâtisserie"], "all_en": ["Depending on the pastry"]},
        ],
    },
    {
        "name_fr": "Boissons", "name_en": "Drinks",
        "subtitle_fr": "Fraîches et chaudes", "subtitle_en": "Cold and hot",
        "dishes": [
            {"name_fr": "Citronnade fait maison", "name_en": "Homemade Lemonade", "price": 3.50,
             "short_fr": "Jus de citron, fleur d'oranger, menthe.",
             "short_en": "Lemon juice, orange blossom, mint.",
             "image": "/images/citronade.jpeg",
             "comp_fr": ["Citron pressé", "Eau de fleur d'oranger", "Menthe fraîche", "Sucre"],
             "comp_en": ["Freshly squeezed lemon", "Orange blossom water", "Fresh mint", "Sugar"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Jus de fruits rouge fait maison", "name_en": "Homemade Red Berry Juice", "price": 4.00,
             "short_fr": "Fruits rouges frais pressés maison.",
             "short_en": "Fresh pressed red berries.",
             "image": "https://i.ibb.co/Z1NYBfjG/Chat-GPT-Image-Jun-11-2026-12-13-48-AM.png",
             "comp_fr": ["Fruits rouges de saison", "Sucre de canne"],
             "comp_en": ["Seasonal red berries", "Cane sugar"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Sodas", "name_en": "Sodas", "price": 2.50,
             "short_fr": "Coca-Cola, Ice Tea, Fanta, Oasis, Orangina, Sprite...",
             "short_en": "Coca-Cola, Ice Tea, Fanta, Oasis, Orangina, Sprite...",
             "image": "https://i.ibb.co/Lz8bPZKR/Chat-GPT-Image-Jun-11-2026-12-29-14-AM.png",
             "comp_fr": ["Coca-Cola", "Ice Tea", "Fanta", "Oasis", "Orangina", "Sprite"],
             "comp_en": ["Coca-Cola", "Ice Tea", "Fanta", "Oasis", "Orangina", "Sprite"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Eau", "name_en": "Water", "price": 2.00,
             "short_fr": "Plate ou gazeuse.",
             "short_en": "Still or sparkling.",
             "image": "/images/evian.jpeg",
             "comp_fr": ["Eau plate ou eau gazeuse"],
             "comp_en": ["Still or sparkling water"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Ayran", "name_en": "Ayran", "price": 2.50,
             "short_fr": "Lait fermenté salé.",
             "short_en": "Salted fermented milk drink.",
             "image": "https://i.ibb.co/xSqLSjMx/Chat-GPT-Image-Jun-11-2026-12-41-53-AM.png",
             "comp_fr": ["Lait fermenté", "Sel"],
             "comp_en": ["Fermented milk", "Salt"],
             "all_fr": ["Lait"], "all_en": ["Milk"]},
            {"name_fr": "Miss Tea", "name_en": "Miss Tea", "price": 2.00,
             "short_fr": "Thé maison aromatisé à la menthe, cannelle, thym et fleur d'oranger.",
             "short_en": "House tea with mint, cinnamon, thyme and orange blossom.",
             "image": "https://i.ibb.co/j9LPwQsC/Chat-GPT-Image-Jun-11-2026-12-47-28-AM.png",
             "comp_fr": ["Thé noir", "Menthe", "Cannelle", "Thym", "Eau de fleur d'oranger"],
             "comp_en": ["Black tea", "Mint", "Cinnamon", "Thyme", "Orange blossom water"],
             "all_fr": [], "all_en": []},
            {"name_fr": "Café by Nespresso", "name_en": "Coffee by Nespresso", "price": 2.50,
             "short_fr": "Expresso ou allongé.",
             "short_en": "Espresso or lungo.",
             "image": "https://i.ibb.co/FbQM4XPY/Chat-GPT-Image-Jun-11-2026-12-50-22-AM.png",
             "comp_fr": ["Expresso", "Allongé"],
             "comp_en": ["Espresso", "Lungo"],
             "all_fr": [], "all_en": []},
        ],
    },
]
